<?php
return array(
	'base'=>array(
		'desc'=>'网站设置',
		'children'=>array(
			'banner'=>'轮播图',
			'seller'=>'商家',
			'product_cate'=>'商品类别',
			'product'=>'商品',
		)
	),
	'user'=>array(
		'desc'=>'安全',
		'children'=>array(
			'menu'=>'菜单',
			'admin_group'=>'权限',
			'admin'=>'管理员',
		)
	),
);